name: Locust Load Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Load Test
        uses: apardo04/locust-github-action@master
        with:
          LOCUSTFILE: /temp/locustfile2.py
          URL:  "https://adrianpardo.dev"
          USERS: "2"
          RATE: "2"
          RUNTIME: "10s"
